package br.com.felipeAplicativos.logica.linguagem;

public enum Text {
//carta
	DE,
//naipe
	ESPADAS, COPAS, PAUS, OUROS,
//cartaValor
	A, J, Q, K,
//logica exceptions
	COD_IMAGEM_EXC, GRANA_PARTIC_EXC,
	NOME_INAVIDO_EXC, PALPITE_INVALIDO_EXCEPTION,
	PARTIC_INEXISTENTE_EXCEPTION,
	VALOR_CARTA_EXCEPTION, VALOR_MODALIDADE_EXCEPTION,
	APOSTA_VOTO_EXECPTION, BOT_PALPITE_EXCEPTION,
	
//FrmLoteria
	LOTERIA_MANEIRA, LINGUAGEM,
//pnlApostas
	INFO_APOSTAS, APOSTAR, CONFIRMAR, BACK, VALOR_DA_APOSTA,
	SELECIONANDO_CARTAS_ALEATORIAMENTE, RESULTADO, PRONTO,
	ALTEROU_O_PALPITE, NAO_ESTA_CONFIRMADO,
//pnlEscolha
	REFAZER, PARTICIPANTE,

//pnlInfoPlayer
	JOGADOR, QUANTO_QUER_APOSTAR, TOTAL,
	
//pnlModoDeJogo
	INFO_MODO_JOGO, MUITO_CURTO, CURTO, MEIO_CURTO, REGULAR,
	DURADOURO, MUITO_DURADOURO,
	
//pnlParticipante
	INFO_PARTICIPANTES, ADICIONAR_PARTICIPANTE, REMOVER_PARTICIPANTE, 
	ESCOLHER_CARTAS, ADICIONAR_DINHEIRO, ADD_BOT, GO,
	
//pnlresultado
	VENCEDORES, PERDEDORES, FALIDOS, VENCEU_COM, PERDEU_COM, 
	FALIU_COM,
	
//mensagens
	//titulos
	FALHA, ENTRADA, TITULO_INFORMACAO, WARNING, BEM_VINDO,
	
	//mensagens
	NENHUM_ITEM_SELECIONADO, INSIRA_SEU_NOME, INSIRA_SUA_GRANA, 
	ADD_GRANA, ESTA_CARTA_JA_ESTA_ESTRE_AS_ESCOLHIDAS,
	SELECAO_DE_CARTAS_COMPLETA_PRESSIONE_CONFIRMAR,
	RAPELOU_TODO_MUNDO_FATURANDO,
	VOCE_FOI_REDIRECIONADO_PARA_TELA_DE_PARTICIPANTES,
	VOCE_NAO_TEM_TODO_ESSE_DINHEIRO,
	INSIRA_A_GRANA_DO_BOT, REGRAS, COMO_JOGAR, 
	UMA_PARTIDA_ESTA_CARREGADA_AGORA_DESEJA_REALMENTE_SAIR,
	
//guiExeptions
	MEMOS_DE_DOIS_JOGADORES_EXCEPTION,
	PALPITE_PENDENTE_EXCEPTION,
}
